/**
 * Auth login
 */
export const LOGIN_AUTH_TYPES = {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT       : 'LOGOUT',
    CLEAR_TOKEN  : 'CLEAR_TOKEN'
};

/**
 * Auth sign up
 */
export const SIGN_UP_AUTH_TYPES = {
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
};

/**
 * Instance
 */
export const INSTANCE = {
    FETCH_INSTANCE_SUCCESS    : 'FETCH_INSTANCE_SUCCESS',
    FETCH_INSTANCE_FAILURE    : 'FETCH_INSTANCE_FAILURE',
    FETCH_NEW_INSTANCE_SUCCESS: 'FETCH_NEW_INSTANCE_SUCCESS',
    FETCH_NEW_INSTANCE_FAILURE: 'FETCH_NEW_INSTANCE_FAILURE',
    DETAIL_INSTANCE           : 'DETAIL_INSTANCE',
    CHANGE_STATUS             : 'CHANGE_STATUS',
    CHANGE_USER               : 'CHANGE_USER',
    CHANGE_PASSWORD           : 'CHANGE_PASSWORD',

};

// export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
// export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// export const LOGOUT        = 'LOGOUT';
// export const CLEAR_TOKEN   = 'CLEAR_TOKEN'